/*
Copyright 2007 BitTorrent, Inc. All rights reserved.
Copyright 2008 Carsten Niebuhr
*/

var LANGUAGES = {
	  "ar"   : "Arabic"
	, "be"   : "Belarusian"
	, "bg"   : "Bulgarian"
	, "bs"   : "Bosnian"
	, "ca"   : "Catalan"
	, "cs"   : "Czech"
	, "da"   : "Danish"
	, "de"   : "German"
	, "el"   : "Greek"
	, "en"   : "English"
	, "es"   : "Spanish"
	, "et"   : "Estonian"
	, "fi"   : "Finnish"
	, "fr"   : "French"
	, "fyNL" : "Frisian"
	, "ga"   : "Gaeilge"
	, "gl"   : "Galician"
	, "he"   : "Hebrew"
	, "hu"   : "Hungarian"
	, "is"   : "Icelandic"
	, "it"   : "Italian"
	, "ja"   : "Japanese"
	, "ka"   : "Georgian"
	, "ko"   : "Korean"
	, "lt"   : "Lithuanian"
	, "lv"   : "Latvian"
	, "nl"   : "Dutch"
	, "nnNO" : "Norwegian Nynorsk"
	, "no"   : "Norwegian"
	, "pl"   : "Polish"
	, "pt"   : "Portuguese (Portugal)"
	, "ptBR" : "Portuguese (Brazil)"
	, "ro"   : "Romanian"
	, "ru"   : "Russian"
	, "sk"   : "Slovak"
	, "sl"   : "Slovenian"
	, "sq"   : "Albanian"
	, "srSR" : "Serbian (Cyrillic)"
	, "sv"   : "Swedish"
	, "th"   : "Thai"
	, "tr"   : "Turkish"
	, "tw"   : "Taiwan"
	, "uk"   : "Ukrainian"
	, "va"   : "Valencian"
	, "vi"   : "Vietnamese"
	, "zhCN" : "Chinese (Simplified)"
	, "zhTW" : "Chinese (Traditional)"
};
